import { HttpRequest, HttpResponseInit, InvocationContext } from '@azure/functions';
import { getReferralContainer, getUsersContainer } from '../lib/cosmos';

/**
 * POST /api/auth/validate-referral
 * Body: { code: string, userId: string, email: string }
 *
 * Validates a referral code during signup. If valid, creates a user record.
 * Referral codes are pre-generated by admin in the 'referrals' container.
 */
export async function validateReferral(
  request: HttpRequest,
  context: InvocationContext
): Promise<HttpResponseInit> {
  try {
    const body = (await request.json()) as {
      code?: string;
      userId?: string;
      email?: string;
      displayName?: string;
    };

    if (!body.code || !body.userId || !body.email) {
      return {
        status: 400,
        jsonBody: { error: 'Missing required fields: code, userId, email' },
      };
    }

    const referralContainer = await getReferralContainer();

    // Look up the referral code
    const { resource: referral } = await referralContainer
      .item(body.code, body.code)
      .read();

    if (!referral) {
      return {
        status: 403,
        jsonBody: { error: 'Invalid referral code' },
      };
    }

    // Check if code is already fully used
    if (referral.maxUses && referral.usedCount >= referral.maxUses) {
      return {
        status: 403,
        jsonBody: { error: 'Referral code has reached maximum uses' },
      };
    }

    // Check if this user already exists
    const usersContainer = await getUsersContainer();
    try {
      const { resource: existingUser } = await usersContainer
        .item(body.userId, body.userId)
        .read();

      if (existingUser) {
        return {
          status: 200,
          jsonBody: { message: 'User already registered', user: existingUser },
        };
      }
    } catch {
      // User doesn't exist yet — this is expected
    }

    // Create user record
    const newUser = {
      id: body.userId,
      userId: body.userId,
      email: body.email,
      displayName: body.displayName || body.email.split('@')[0],
      referralCode: body.code,
      createdAt: new Date().toISOString(),
      settings: {},
    };

    await usersContainer.items.create(newUser);

    // Increment referral usage count
    referral.usedCount = (referral.usedCount || 0) + 1;
    referral.usedBy = [...(referral.usedBy || []), body.userId];
    await referralContainer.item(referral.id, referral.code).replace(referral);

    context.log(`User ${body.userId} registered with referral code ${body.code}`);

    return {
      status: 201,
      jsonBody: { message: 'User registered successfully', user: newUser },
    };
  } catch (error: any) {
    context.error('validateReferral error:', error);
    return {
      status: 500,
      jsonBody: { error: 'Internal server error' },
    };
  }
}
